/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/tenants/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mine */
        get: operations["list_mine_tenants_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Tenant */
        get: operations["get_current_tenant_tenants_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Current Tenant */
        patch: operations["rename_current_tenant_tenants_current_patch"];
        trace?: never;
    };
    "/tenants/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_tenants_members_get"];
        put?: never;
        /** Add Member */
        post: operations["add_member_tenants_members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_tenants_members__user_id__delete"];
        options?: never;
        head?: never;
        /** Change Member Role */
        patch: operations["change_member_role_tenants_members__user_id__patch"];
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Catalog Entries */
        get: operations["list_catalog_entries_catalog_get"];
        put?: never;
        /** Create Catalog Entry */
        post: operations["create_catalog_entry_catalog_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog Entry */
        get: operations["get_catalog_entry_catalog__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Catalog Entry */
        delete: operations["delete_catalog_entry_catalog__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Catalog Entry */
        patch: operations["update_catalog_entry_catalog__entry_id__patch"];
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Devices */
        get: operations["list_devices_devices_get"];
        put?: never;
        /** Create Device */
        post: operations["create_device_devices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Device */
        get: operations["get_device_devices__device_id__get"];
        put?: never;
        post?: never;
        /** Delete Device */
        delete: operations["delete_device_devices__device_id__delete"];
        options?: never;
        head?: never;
        /** Update Device */
        patch: operations["update_device_devices__device_id__patch"];
        trace?: never;
    };
    "/devices/{device_id}/rotate-credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate Credential */
        post: operations["rotate_credential_devices__device_id__rotate_credential_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_devices__device_id__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data */
        get: operations["data_devices__device_id__data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description HTTP REST ingest fallback (CLAUDE.md's device contract, §3's "HTTP REST
         *     ingest exists as a fallback"). Same device credentials as MQTT, same
         *     verification path (auth_service.verify_secret), same Redis stream as the
         *     MQTT ingest path — one normalization path, not two.
         */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/emqx/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emqx Authenticate */
        post: operations["emqx_authenticate_ingestion_emqx_authenticate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/emqx/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emqx Authorize */
        post: operations["emqx_authorize_ingestion_emqx_authorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_devices__device_id__rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_devices__device_id__rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Rules */
        get: operations["list_all_rules_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule */
        get: operations["get_rule_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule */
        patch: operations["update_rule_rules__rule_id__patch"];
        trace?: never;
    };
    "/devices/{device_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Commands */
        get: operations["list_commands_devices__device_id__commands_get"];
        put?: never;
        /** Request Command */
        post: operations["request_command_devices__device_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dashboards */
        get: operations["list_dashboards_dashboards_get"];
        put?: never;
        /** Create Dashboard */
        post: operations["create_dashboard_dashboards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboards/{dashboard_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboards__dashboard_id__get"];
        put?: never;
        post?: never;
        /** Delete Dashboard */
        delete: operations["delete_dashboard_dashboards__dashboard_id__delete"];
        options?: never;
        head?: never;
        /** Update Dashboard */
        patch: operations["update_dashboard_dashboards__dashboard_id__patch"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_notifications_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark Read */
        patch: operations["mark_read_notifications__notification_id__read_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActuatorCommandAction */
        ActuatorCommandAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "actuator_command";
            /** Actuator */
            actuator: string;
            /** Value */
            value: boolean | number | string;
        };
        /** AddMemberRequest */
        AddMemberRequest: {
            /** Email */
            email: string;
            /** @default viewer */
            role: components["schemas"]["TenantRole"];
        };
        /** ApiKeyCreateRequest */
        ApiKeyCreateRequest: {
            /** Name */
            name: string;
            /** @default viewer */
            role: components["schemas"]["TenantRole"];
        };
        /** ApiKeyCreateResponse */
        ApiKeyCreateResponse: {
            api_key: components["schemas"]["ApiKeyResponse"];
            /**
             * Key
             * @description The full secret — shown once, never retrievable again
             */
            key: string;
        };
        /** ApiKeyResponse */
        ApiKeyResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** CatalogActuator */
        CatalogActuator: {
            /** Name */
            name: string;
            /** Key */
            key?: string | null;
            /**
             * Value Type
             * @default bool
             * @enum {string}
             */
            value_type: "bool" | "float" | "string";
            /** Allowed Values */
            allowed_values?: (boolean | number | string)[] | null;
            /** On Value */
            on_value?: boolean | number | string | null;
            /** Off Value */
            off_value?: boolean | number | string | null;
        };
        /** CatalogEntryCreateRequest */
        CatalogEntryCreateRequest: {
            /** Name */
            name: string;
            /** Metrics */
            metrics?: components["schemas"]["CatalogMetric"][];
            /** Actuators */
            actuators?: components["schemas"]["CatalogActuator"][];
        };
        /** CatalogEntryResponse */
        CatalogEntryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Metrics */
            metrics: components["schemas"]["CatalogMetric"][];
            /** Actuators */
            actuators: components["schemas"]["CatalogActuator"][];
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "disabled";
            /** Is Legacy */
            is_legacy: boolean;
            /** Device Count */
            device_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CatalogEntryUpdateRequest */
        CatalogEntryUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Metrics */
            metrics?: components["schemas"]["CatalogMetric"][] | null;
            /** Actuators */
            actuators?: components["schemas"]["CatalogActuator"][] | null;
            /** Status */
            status?: ("active" | "disabled") | null;
        };
        /** CatalogMetric */
        CatalogMetric: {
            /** Name */
            name: string;
            /** Key */
            key?: string | null;
            /** Unit */
            unit?: string | null;
            /**
             * Data Type
             * @default float
             * @enum {string}
             */
            data_type: "float" | "bool";
            /** Decimals */
            decimals?: number | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
        /** ChangeRoleRequest */
        ChangeRoleRequest: {
            role: components["schemas"]["TenantRole"];
        };
        /** CommandResponse */
        CommandResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Rule Id */
            rule_id: string | null;
            /** Actuator */
            actuator: string;
            /** Value */
            value: unknown;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Ttl Seconds */
            ttl_seconds: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Acked At */
            acked_at: string | null;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ConditionGroup */
        "ConditionGroup-Input": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "group";
            /**
             * Op
             * @enum {string}
             */
            op: "AND" | "OR";
            /** Predicates */
            predicates: (components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Input"])[];
        };
        /** ConditionGroup */
        "ConditionGroup-Output": {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "group";
            /**
             * Op
             * @enum {string}
             */
            op: "AND" | "OR";
            /** Predicates */
            predicates: (components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Output"])[];
        };
        /** ConditionLeaf */
        ConditionLeaf: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "leaf";
            /** Metric */
            metric: string;
            /** Operator */
            operator: string;
            /** Threshold */
            threshold: number;
            /**
             * Hysteresis
             * @default 0
             */
            hysteresis: number;
        };
        /** DashboardCreateRequest */
        DashboardCreateRequest: {
            /** Name */
            name: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Layout */
            layout: components["schemas"]["Widget"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DashboardUpdateRequest */
        DashboardUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Layout */
            layout?: components["schemas"]["Widget"][] | null;
        };
        /** DeviceCreateRequest */
        DeviceCreateRequest: {
            /** Name */
            name: string;
            /**
             * Catalog Entry Id
             * Format: uuid
             */
            catalog_entry_id: string;
        };
        /** DeviceCreateResponse */
        DeviceCreateResponse: {
            device: components["schemas"]["DeviceResponse"];
            credential: components["schemas"]["DeviceCredential"];
            /** Tenant Slug */
            tenant_slug: string;
        };
        /**
         * DeviceCredential
         * @description The MQTT credential — present only in create/rotate responses, never in
         *     list/get responses. The password is shown once and cannot be retrieved again.
         */
        DeviceCredential: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** DeviceResponse */
        DeviceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Catalog Entry Id
             * Format: uuid
             */
            catalog_entry_id: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Last Seen At */
            last_seen_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Connection State
             * @enum {string}
             */
            connection_state: "online" | "offline" | "never_connected";
        };
        /**
         * DeviceStatus
         * @enum {string}
         */
        DeviceStatus: "active" | "disabled";
        /** DeviceUpdateRequest */
        DeviceUpdateRequest: {
            /** Name */
            name?: string | null;
            status?: components["schemas"]["DeviceStatus"] | null;
        };
        /** EmqxAuthenticateRequest */
        EmqxAuthenticateRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** EmqxAuthenticateResponse */
        EmqxAuthenticateResponse: {
            /** Result */
            result: string;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
        };
        /** EmqxAuthorizeRequest */
        EmqxAuthorizeRequest: {
            /** Username */
            username: string;
            /** Topic */
            topic: string;
            /** Action */
            action: string;
        };
        /** EmqxAuthorizeResponse */
        EmqxAuthorizeResponse: {
            /** Result */
            result: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestRequest
         * @description Body for the HTTP REST ingest fallback. The device itself is identified
         *     by its Basic-auth credentials, not by anything in the body.
         */
        IngestRequest: {
            /** Metric */
            metric: string;
            /** Value */
            value: number;
            /** Timestamp */
            timestamp?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ManualCommandRequest
         * @description A dashboard-triggered actuator toggle (Phase 4) — validated the same
         *     as any other HTTP boundary input before commands.service.request_manual_command
         *     ever sees it.
         */
        ManualCommandRequest: {
            /** Actuator */
            actuator: string;
            /** Value */
            value: boolean | number | string;
        };
        /** MemberResponse */
        MemberResponse: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** MembershipSummary */
        MembershipSummary: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Tenant Slug */
            tenant_slug: string;
            /** Role */
            role: string;
        };
        /** NotificationAction */
        NotificationAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "notification";
            /** Message */
            message: string;
        };
        /** NotificationResponse */
        NotificationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Device Id */
            device_id: string | null;
            /** Rule Id */
            rule_id: string | null;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read At */
            read_at: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Tenant Name */
            tenant_name: string;
            /** Name */
            name?: string | null;
        };
        /** RuleCreateRequest */
        RuleCreateRequest: {
            /** Condition */
            condition: components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Input"];
            /**
             * For Duration
             * @default 0
             */
            for_duration: number;
            /**
             * Cooldown
             * @default 0
             */
            cooldown: number;
            /** Action */
            action: components["schemas"]["ActuatorCommandAction"] | components["schemas"]["NotificationAction"] | components["schemas"]["WebhookAction"];
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** RuleResponse */
        RuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Type */
            type: string;
            /** Condition */
            condition: components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Output"];
            /** For Duration */
            for_duration: number;
            /** Cooldown */
            cooldown: number;
            /** Action */
            action: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RuleUpdateRequest */
        RuleUpdateRequest: {
            /** Condition */
            condition?: (components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Input"]) | null;
            /** For Duration */
            for_duration?: number | null;
            /** Cooldown */
            cooldown?: number | null;
            /** Action */
            action?: (components["schemas"]["ActuatorCommandAction"] | components["schemas"]["NotificationAction"] | components["schemas"]["WebhookAction"]) | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * RuleWithDeviceResponse
         * @description The tenant-wide /rules list needs to say which device each rule
         *     belongs to — the per-device endpoints don't, since the device is already
         *     implied by the URL.
         */
        RuleWithDeviceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Type */
            type: string;
            /** Condition */
            condition: components["schemas"]["ConditionLeaf"] | components["schemas"]["ConditionGroup-Output"];
            /** For Duration */
            for_duration: number;
            /** Cooldown */
            cooldown: number;
            /** Action */
            action: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Device Name */
            device_name: string;
            /** Device Slug */
            device_slug: string;
        };
        /** TelemetryDataPoint */
        TelemetryDataPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Value */
            value: number;
        };
        /** TelemetryDataResponse */
        TelemetryDataResponse: {
            /** Metric */
            metric: string;
            /** Resolution */
            resolution: string;
            /** Points */
            points: components["schemas"]["TelemetryDataPoint"][];
        };
        /** TelemetryLatestResponse */
        TelemetryLatestResponse: {
            /** Metric */
            metric: string;
            /** Value */
            value: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
        };
        /** TenantCreateRequest */
        TenantCreateRequest: {
            /** Name */
            name: string;
        };
        /** TenantResponse */
        TenantResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TenantRole
         * @description A member's role within a tenant.
         *
         *     Stored as plain text + a CHECK constraint (not a native Postgres ENUM) so
         *     adding a role later is a one-line migration rather than an ALTER TYPE.
         * @enum {string}
         */
        TenantRole: "owner" | "admin" | "viewer";
        /** TenantUpdateRequest */
        TenantUpdateRequest: {
            /** Name */
            name: string;
        };
        /** TokenPairResponse */
        TokenPairResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipSummary"][];
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Name */
            name?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookAction */
        WebhookAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "webhook";
            /** Url */
            url: string;
            /** Body */
            body?: {
                [key: string]: unknown;
            };
        };
        /**
         * Widget
         * @description One grid item. Kept deliberately loose — a widget referencing a
         *     nonexistent or foreign device just renders an error/empty state
         *     client-side the next time it fetches through the normal tenant-scoped
         *     device endpoints, so there's no server-side cross-referencing to do here.
         */
        Widget: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "value_card" | "trend_chart" | "device_status" | "actuator_control" | "gauge";
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Metric */
            metric?: string | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mine_tenants_mine_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_tenants_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_tenant_tenants_current_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_current_tenant_tenants_current_patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_tenants_members_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_tenants_members_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_tenants_members__user_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_member_role_tenants_members__user_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_catalog_entries_catalog_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_catalog_entry_catalog_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogEntryCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_entry_catalog__entry_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_catalog_entry_catalog__entry_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_catalog_entry_catalog__entry_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogEntryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_devices_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_device_devices_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_devices__device_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_device_devices__device_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_device_devices__device_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_credential_devices__device_id__rotate_credential_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_keys_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_key_api_keys_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_devices__device_id__latest_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryLatestResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_devices__device_id__data_get: {
        parameters: {
            query: {
                metric: string;
                from: string;
                to?: string | null;
                resolution?: string;
            };
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emqx_authenticate_ingestion_emqx_authenticate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-emqx-auth-secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmqxAuthenticateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmqxAuthenticateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emqx_authorize_ingestion_emqx_authorize_post: {
        parameters: {
            query?: never;
            header?: {
                "x-emqx-auth-secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmqxAuthorizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmqxAuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_devices__device_id__rules_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_devices__device_id__rules_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_rules_rules_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleWithDeviceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_rules__rule_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_commands_devices__device_id__commands_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_command_devices__device_id__commands_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dashboards_dashboards_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dashboard_dashboards_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_dashboards__dashboard_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dashboard_dashboards__dashboard_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dashboard_dashboards__dashboard_id__patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                dashboard_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_notifications_read_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_notifications__notification_id__read_patch: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
                authorization?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
